




.build/atmega328/src/trigger_riot.cpp : src/trigger_riot.ino
	@mkdir -p .build/atmega328/src
	@echo [93msrc/trigger_riot.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/atmega328/src/trigger_riot.cpp
	@true

